// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPljkRVc9dPH-1WIsqIR_sPU4UwuAG_SU',
    appId: '1:294821950870:web:bde859e2bb622b87b519b7',
    messagingSenderId: '294821950870',
    projectId: 'mldigitalschool',
    authDomain: 'mldigitalschool.firebaseapp.com',
    storageBucket: 'mldigitalschool.appspot.com',
    measurementId: 'G-6KDBKEM203',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgHO30thQIYNcJMhSZmbLxphD-dXbdgnI',
    appId: '1:294821950870:android:b815a5a751448684b519b7',
    messagingSenderId: '294821950870',
    projectId: 'mldigitalschool',
    storageBucket: 'mldigitalschool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCSpIBTZlLQ6CNqmSA2awjLSFqGaHGaw',
    appId: '1:294821950870:ios:ceab415a96423587b519b7',
    messagingSenderId: '294821950870',
    projectId: 'mldigitalschool',
    storageBucket: 'mldigitalschool.appspot.com',
    iosClientId: '294821950870-b9kptbbdmfa6u101fkv316eejdack1t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mldisgitalschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeCSpIBTZlLQ6CNqmSA2awjLSFqGaHGaw',
    appId: '1:294821950870:ios:ceab415a96423587b519b7',
    messagingSenderId: '294821950870',
    projectId: 'mldigitalschool',
    storageBucket: 'mldigitalschool.appspot.com',
    iosClientId: '294821950870-b9kptbbdmfa6u101fkv316eejdack1t5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mldisgitalschool',
  );
}
